config/routes.rb
Rails.application.routes.draw do
 
  resources :links
  resources :products
  resources :brands
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
   #nos dice donde estan las sessions
 devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
      get "admins/user/list",
      to: "admins/sessions#list",
      as: "list_user"
  end
  
  resources :brands do
  resources :products
      end

resources :products do
  member do
    put "like", to: "products#upvote"
    put "dislike", to: "products#downvote"
  end
end



 # get "users/list", to: "brands#user", as: "list_user"
    root to: 'brands#index'
 # get '/sexto/cerebros',to: 'products#index', as: 'products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products
    belongs_to :user
  
    
    validates :name, presence: true, length: { maximum: 30 }
    validates :owner, presence: true, length: { maximum: 30 }
    validates :range, presence: true, length: { maximum: 7 }
    validates :avatar, presence: true
    
    mount_uploader :avatar, AvatarUploader
    
    
#    class EmailValidator < ActiveModel::EachValidator
#      def validate_each(record, attribute, value)
#        unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#          record.errors[attribute] << (options[:message] || "No es un E-Mail")
#        end
#      end
#    end
#    validates :email, email: true
    
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
		if current_admin
				@brands = Brand.all
		elsif current_user
			role = current_user.role
			if role == "contributor"
				@brands = Brand.where(user_id:current_user.id)
		else    
			@brands = Brand.all
		end
     end
   end

def user
    @users = User.all
end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
  	role= current_user.role
      if role == "suscriber"
		      flash[:notice]= "You're not able to create a Brand"
		      redirect_to brand_path
      else    
    	    @brands = Brand.new
    	end
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brandss
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)
   	# @product= @brand.products.create(product_params)
	  @brand.user_id = current_user.id 

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :owner, :range, :crueltly, :avatar)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for Brand.new do |f| %>

	<div class="row">
		<div class="large-6 columns">
			<div class="field">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>

			<div class="field">
				<%= f.label :range %>
				<%= f.text_field :range %>
			</div>

			<div class="field">
				<%= f.label :crueltly %>
				<%= f.check_box :crueltly %>
			</div>
		</div>
	
		<div class="large-6 columns">
			<div class="field">
				<%= f.label :owner %>
				<%= f.text_field :owner %>
			</div>
			<div class="field">
				<%= f.label :avatar %>
				<%= f.file_field :avatar %>
			</div>
		</div>
	</div>
		
		<div class="actions">
			<%= f.submit class:'button warning'%>
		</div>
	
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<br>
<h1>The Brands</h1>
<% if admin_signed_in?||current_user.role == "editor" %>
	<table>
		<thead>
			<tr>
			<th>Avatar</th>
			<th>Name</th>
			<th>Owner</th>
			<th>Range</th>
			<th>Crueltly</th>
			<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @brands.each do |brand| %>
			<tr>
				<td><%= image_tag(brand.avatar_url, class: 'brandAvatarAdmin') if brand.avatar? %> </td>
				<td><%= brand.name %></td>
				<td><%= brand.user_id ? User.find(brand.user_id).email : "Without owner" %> </td>
				<td><%= brand.range %></td>
				<td><%= brand.crueltly %></td>
				<td><%= link_to 'Show', brand,class:'button primary' %></td>
				<td><%= link_to 'Edit', edit_brand_path(brand), class:'button warning'%></td>
				<td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' },class:'button alert' %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	<%= link_to 'New Brand', new_brand_path,class:'button success' %>
	
<% else %>
<% @brands.each do |brand| %>
	<tr>
	<%= link_to brand do %>
		<td> <%= image_tag(brand.avatar_url, class: 'brandAvatar') if brand.avatar? %> </td>
	<% end %>
	</tr>
<% end %>

<%end%>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path,class:'button secondary' %>

app/views/brands/show.html.erb
<br> <br>
<div class="row">
	<div class="field large-2 columns ">
	</div>
    <div class="field large-4 columns bigima">
        <%= image_tag(@brand.avatar_url, class: 'bigima') if @brand.avatar? %>
    </div>

    <div class="field large-6 columns">

		<p id="notice"><%= notice %></p>

		<p>
		<strong>Name:</strong>
		<%= @brand.name %>
		</p>

		<p>
		<strong>Owner:</strong>
		<%= @brand.user_id ? User.find(@brand.user_id).email : "Without owner" %>
		</p>

		<p>
		<strong>Range:</strong>
		<%= @brand.range %>
		</p>

		<p>
		<strong>Crueltly:</strong>
		<%= @brand.crueltly %>
		</p>
	</div>

</div>

<div class="row Products">
	<h2>Products</h2>
	<div id="products" class="field large-12 columns">
		<%= render :partial => @brand.products.reverse %>
	</div>

	<% if admin_signed_in?||user_signed_in? %>
		<% if current_user.role == "contributor" %>

			<div id="products" class="field large-9 ">
				<h2>Add Product</h2>
				<%= form_for([@brand, Product.new], remote: true) do |f| %>
					
				<div class="field large-4 columns">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>
			
				<div class="field large-2  columns">
					<%= f.label :color %>
					<%= f.text_field :color %>
				</div>

				<div class="field large-4 columns">
					<%= f.label :kind %>
					<%= f.text_field :kind %>
				</div>

				<div class="field large-2  columns">
					<%= f.label :unitprice %>
					<%= f.text_field :unitprice %>
				</div>
				
				<div class="field">
					<%= f.label :avatar %>
					<%= f.file_field :avatar %>
				</div>
				
				
				<div class="actions large-3 columns ">
					<%= f.submit 'Create Product', class:'button warning' %>
				</div>
			
			</div>
		<% end %>
	<% end %>
	
 	</div>
<% end %>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>