config/routes.rb
Rails.application.routes.draw do
 
  resources :links
  resources :products
  resources :brands
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
   #nos dice donde estan las sessions
 devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
      get "admins/user/list",
      to: "admins/sessions#list",
      as: "list_user"
  end
  
  resources :brands do
  resources :products
      end

resources :products do
  member do
    put "like", to: "products#upvote"
    put "dislike", to: "products#downvote"
  end
end



 # get "users/list", to: "brands#user", as: "list_user"
    root to: 'brands#index'
 # get '/sexto/cerebros',to: 'products#index', as: 'products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :brand

    mount_uploader :avatar, AvatarUploader
    def score
        self.get_upvotes.size - self.get_downvotes.size
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show], unique: [:session_hash]
  protect_from_forgery with: :null_session

  # GET /products
  # GET /products.json
  def index
    @products = Product.all    
  end
  def upvote
    @product = Product.find(params[:id])
    @product.upvote_by current_user
    redirect_to product_path
  end

  def downvote
    @product = Product.find(params[:id])
    @product.downvote_by current_user
    redirect_to product_path
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    impressionist(@product)
  end

  # GET /products/new
  def new
    @product = Product.new
    @brands = Brand.all
  end

  # GET /products/1/edit
  def edit
  end

  def upvote 
    @product = Product.find(params[:id])
    @product.upvote_by current_user
    redirect_to :back
  end  
  
  def downvote
    @product = Product.find(params[:id])
    @product.downvote_by current_user
    redirect_to :back
  end

  # POST /products
  # POST /products.json
  def create
    #@product = Product.new(product_params)
      @brand = Brand.find(params[:brand_id]);
      @product = @brand.products.create(product_params);

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:brand_id,:name, :color, :kind, :unitprice, :avatar, :impressions_count)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% options = options_from_collection_for_select(Brand.all, 'id', 'name')%>
    <%= select_tag("product[brand_id]", options)%>    
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>


  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>


   <div class="field">
    <%= f.label :kind %>
    <%= f.text_area :kind %>
  </div>

  <div class="field">
    <%= f.label :unitprice %>
    <%= f.text_field :unitprice %>
  </div>

  <div class="field">
			<%= f.label :avatar %>
			<%= f.file_field :avatar  %>
		</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
    
<% if admin_signed_in? ||current_user.role == "contributor" %> 
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Color</th>
            <th>Price</th>
            <th>Avatar</th>
            <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
            <tr>
            <td><%= product.name %></td>
            <td><%= product.color %></td>
            <td><%= product.unitprice %></td>
            <td> <%= image_tag(product.avatar_url, class: 'brandAvatarPContri') if product.avatar? %> </td>
            <td><%= link_to 'Show', product,class:'button primary' %></td>
            <td><%= link_to 'Edit', edit_product_path(product) ,class:'button warning'%></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class:'button alert' %></td>
            </tr>
        </tbody>
    </table>

<% else %>
    <tr>
        <%= link_to product do %>
            <td> <%= image_tag(product.avatar_url, class: 'brandAvatarP') if product.avatar? %> </td>
        <% end %>
    </tr>
<% end %>

app/views/products/create.js.erb
var new_product = $("<%= escape_javascript(render(:partial => @product)) %>").hide();
$('#products').prepend(new_product);
$('#product_<%= @product.id %>').fadeIn('slow');
$('#new_product')[0].reset();

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Their Products</h1>
<% if admin_signed_in?||current_user.role == "editor" %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Price</th>
        <th>Avatar</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @brand= Brand.all%>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.color %></td>
          <td><%= product.unitprice %></td>
          <td> <%= image_tag(product.avatar_url, class: 'brandAvatarPContri') if product.avatar? %> </td>
          <td><%= link_to 'Show', product,class:'button primary' %></td>
          <td><%= link_to 'Edit', edit_product_path(product),class:'button warning' %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class:'button alert' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Product', new_product_path,class:'button success' %>
	
<% else %>
 <% @products.each do |product| %>
    <tr>
    <%= link_to product do %>
      <td> <%= image_tag(product.avatar_url, class: 'brandAvatar') if product.avatar? %> </td>
    <% end %>
    </tr>
    <% end %>
<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path,class:'button secondary' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="field large-5 columns">
	<p>
		<%= image_tag(@product.avatar_url, class: 'productAvatar') if @product.avatar? %> 
	</p>
</div>
<div class="row">
	<div class="field large-3 columns">
	<h4>
		<strong>Name:</strong>
		<%= @product.name %>
	</h4>
	<h4>
		<strong>Color:</strong>
		<%= @product.color %>
	</h4>
	<h4>
		<strong>Price:</strong>
		<%= @product.unitprice %>
	</h4>
	</div>
	<div class="field large-3 columns">
	<h4>
		<strong>Review:</strong>
		<%= @product.kind %>
	</h4>
	</div>
	<div class="field large-5 columns">
		<h5>
			<%= "#{@product.impressionist_count(:filter=>:session_hash)} views" %>
		</h5>
		<br><br>
		<h5>
			<%= link_to "Like", like_product_path(@product), method: :put,class:'button primary'  %>
			<%= link_to "Dislike", dislike_product_path(@product), method: :put,class:'button secondary'  %>
			
			</h5>
			<h6>
			Puntaje
			<%= @product.score %>
			</h6>
		
	</div>
</div>


<%= link_to 'Edit', edit_product_path(@product),class:'button warning' %> |
<%= link_to 'Back', brands_path(@brand_id) ,class:'button secondary' %>