config/routes.rb
Rails.application.routes.draw do
 
  resources :links
  resources :products
  resources :brands
  devise_for :users, controllers:{
    sessions: 'users/sessions'
  }
   #nos dice donde estan las sessions
 devise_for :admins, controllers:{
    sessions: 'admins/sessions'
  }
  devise_scope :admin do
      get "admins/user/list",
      to: "admins/sessions#list",
      as: "list_user"
  end
  
  resources :brands do
  resources :products
      end

resources :products do
  member do
    put "like", to: "products#upvote"
    put "dislike", to: "products#downvote"
  end
end



 # get "users/list", to: "brands#user", as: "list_user"
    root to: 'brands#index'
 # get '/sexto/cerebros',to: 'products#index', as: 'products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>MakeUp Review</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<% if user_signed_in? %>
    <div class="top-bar">
        <div class="top-bar-left">
           
                    <ul class="menu">
                        <% if current_user.role == "suscriber" %>
                            <li><%= link_to "Index brands", brands_path %></li>
                        <% else %>
                            <li><%= link_to "Index brands", brands_path %></li>
                            <li><%= link_to "New brand", new_brand_path %></li>
                        <%end%>
                            
                    </ul>
                
        </div>
       

        <div class="top-bar-right">
         <ul class="menu">
            <% if user_signed_in? %>
                 <li>Bienvenido(a) <%= current_user.email %>  </li>
                <br>    
                <li><%= link_to "Editar perfil", edit_admin_registration_path %></li>
                <li><%= link_to "Cerrar sesion", destroy_admin_session_path, method: :delete%></li>
                <% else %>
                <li><%= link_to "Login", new_admin_session_path %></li>
                <li><%= link_to "Registro", new_admin_registration_path %></li>
                <%end%>
                
                </ul>    
      </div> 
    </div>
<% end %>

<% if admin_signed_in? %>
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        
            <li class="menu-text">
                <a href="#">Brands</a>
                <ul class="menu">
                        <li><%= link_to "New brand", new_brand_path %></li>
                        <li><%= link_to "Index brands", brands_path %></li>
                        
                </ul>
            </li>
        </ul>
    </div>
   

    <div class="top-bar-right">
     <ul class="menu">
        <% if admin_signed_in? %>
            
            <br>    
            <li><%= link_to "Editar perfil", edit_admin_registration_path %></li>
            <li><%= link_to "Cerrar sesion", destroy_admin_session_path, method: :delete%></li>
        <% else %>
            <li><%= link_to "Login", new_admin_session_path %></li>
            <li><%= link_to "Registro", new_admin_registration_path %></li>
        <%end%>
            
            </ul>    
  </div> 
</div>
<% end %>


   

    <% if notice %>
        <p class="alert alert-success"><%= notice%></p>
    <% end%>

    <% if alert%>
        <p class="alert alert-danger"><%= alert %> </p>
    <% end %>


    <%= yield %>

  </body>
</html>